version: 2

project_name: riot

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: riot
    main: ./cmd/riot
    binary: riot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}
      - -X main.builtBy=goreleaser

archives:
  - id: riot-unix
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

  - id: riot-windows
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    formats:
      - zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "typo"
  groups:
    - title: "New Features"
      regexp: "^feat:"
      order: 0
    - title: "Bug Fixes"
      regexp: "^fix:"
      order: 1
    - title: "Performance Improvements"
      regexp: "^perf:"
      order: 2
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: fabianopinto
    name: riot
  draft: false
  prerelease: auto
  mode: append
  footer: |
    ## Installation

    ### Using go install
    ```bash
    go install github.com/fabianopinto/riot/cmd/riot@{{ .Tag }}
    ```

    ### Using Binary
    Download the appropriate binary for your platform from the assets below.

homebrew_casks:
  - name: riot
    ids:
      - riot-unix
    url:
      template: "https://github.com/fabianopinto/riot/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/fabianopinto/riot
    description: "RIoT - A Go application"
    repository:
      owner: fabianopinto
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

sboms:
  - id: archieve
    artifacts: archive
    ids:
      - riot-unix
    documents:
      - "${artifact}.sbom.json"

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
